apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/chevalsumo/data-platform.git
    path: charts/airflow/
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true